# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c586dbe05b4787b9da79cd9d0f2ed02f3feb9e0096738b4ffe8740de003024f2726539a9a930c1b742cdb4b24797175542cf6397c9e55ccc654898056887efd8

test:
  secret_key_base: d94dfea4147fe11f8f5c6c0c868eb0e88672688a0df3b4460e9a61ecce7bd9313c71f16507fa0ec8a111934da082b2c55ce0c7108a02528d0cf187958d1c3052

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
